<<<<<<< HEAD
services:
  - type: web
    name: planealo-app
    runtime: php
    plan: free
    rootDirectory: web  # Cambiado a 'web' para Yii2 Basic
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php yii migrate --interactive=0
    startCommand: php -S 0.0.0.0:$PORT -t web  # Sirve desde 'web'
    envVars:
      - key: YII_ENV
        value: prod
      - key: YII_DEBUG
        value: "false"
      - key: DB_DSN
        fromDatabase:
          name: planealo-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: planealo-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: planealo-db
          property: password
=======
# render.yaml
services:
  - type: web
    name: planealo-web
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php init --env=Production --overwrite=All
    startCommand: php -S 0.0.0.0:$PORT -t web
    envVars:
      - key: YII_ENV
        value: production
      - key: YII_DEBUG
        value: false
>>>>>>> origin/mjbv-oficina

  - type: pgsql
    name: planealo-db
    plan: free
<<<<<<< HEAD
    databaseName: planealo
    ipAllowList: []
=======
    ipAllowList: []
    databaseName: planealo
    user: planealo_user
>>>>>>> origin/mjbv-oficina
